version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "f6:f7:d9:cf:34:03:0e:97:c1:d4:f3:88:d4:26:8f:95"
      - run:
        name: Build Docker Image
        command: docker build -t $IMAGE_NAME .
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMAGE_NAME
      - run:
          name: Deploy
          command: |
            ssh-keyscan -t rsa $HOST >> ~/.ssh/known_hosts
            ssh $USER@$HOST < deploy.sh